title: Aman Abhishek
logo: /assets/img/photo.jpeg
description: PhD student at the School of Journalism & Mass Communication at the University of Wisconsin-Madison
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
