title: Aman Abhishek
logo: /assets/img/photo.jpeg
description: Graduate student in media studies at University of Wisconsin-Madison
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
